### ISSUE TITLE
Get list of holidays of the current month

### ISSUE THREAD

**Issue by bukinoshita** [bukinoshita/is-holiday#1]
Check the [API](https://github.com/bukinoshita/holiday)

Should return something like this:

```bash
Holidays in January:
----
⇢ 1: New Years Day
⇢ 2: New Years Day Holiday
⇢ 16: Martin Luther King Day
```

Where the `Holidays in January` and the day are bold. (Use [chalk](https://github.com/chalk/chalk))

**Comment by vcapretz** [comment]
created pull request https://github.com/bukinoshita/is-holiday/pull/2
