### ISSUE TITLE
Get list of holidays of the current year

### ISSUE THREAD

**Issue by bukinoshita** [bukinoshita/is-holiday#8]
We can get a list of holidays of the whole year now on [holiday v0.0.2](https://github.com/bukinoshita/holiday/releases/tag/v0.0.2).

Should something like this:
```bash
Holidays in 2017:
----
January:
⇢ 1: New Years Day
⇢ 2: New Years Day Holiday
⇢ 16: Martin Luther King Day

February:
⇢ 1: New Years Day
⇢ 2: New Years Day Holiday
⇢ 16: Martin Luther King Day

Where `Holidays in 2017:`, `January:` and `⇢ 1:` are bold.

**Comment by nicheProgramming** [comment]
I would like to contribute to this, but I have a few questions. What is the desired change? I may be misreading but this appears to be a statement. Are you looking for a master US Holiday list formatted as you have shown in this example? and if so, what file would you like it in?

**Comment by bukinoshita** [comment]
Hello @nicheProgramming! Yea, the issue is not self explanatory, sorry about that.

So, when the user runs `is-holiday -y` or `is-holiday --year` it should show every holiday in the current year.

```
is-holiday -y
// => should return every US holiday in 2017 (current year and default country is US)
```

As you can see on [this file](https://github.com/bukinoshita/is-holiday/blob/master/index.js#L64-L68) @vcapretz did a great job for month list. It's the same idea but for year. And [this](https://github.com/bukinoshita/holiday) is the library that we use to get the holiday list.

Let me know if you have any questions

**Comment by jylopez** [comment]
Hi, I added a March holiday and made a pull request to your [holiday](https://github.com/bukinoshita/holiday) repo. `is-holiday` was failing because you didn't have a March holiday.

**Comment by nicheProgramming** [comment]
If anyone else wants to take this issue, please do. I unfortunately will not be able to. Best of luck!

**Comment by vcapretz** [comment]
I'll be taking that one @bukinoshita

**Comment by bukinoshita** [comment]
Thanks @nicheProgramming. Go for it @vcapretz 👍

**Comment by bukinoshita** [comment]
hey @vcapretz are you willing to do this? Otherwise I might take it.

**Comment by bukinoshita** [comment]
Done on [v0.0.2](https://github.com/bukinoshita/is-holiday/releases/tag/v0.0.2)
